name: Deploy Static Site to S3

on:
  push:
    branches:
      - main  # Trigger workflow only when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Get the latest code
        uses: actions/checkout@v4

      # Step 2: Install AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Step 3: Configure AWS credentials
      - name: Configure AWS
        run: aws configure set region $AWS_DEFAULT_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_BUCKET_REGION }}

      # Step 4: Deploy site files to S3
      - name: Upload website files to S3
        run: |
          echo "Starting upload to S3..."
          aws s3 sync ./ s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exact-timestamps \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md" \
            --only-show-errors
          echo "Upload finished!"
