name: Deploy Static Website to S3

on:
  push:
    branches:
      - main  # runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Deploy to S3
      - name: Upload to S3
        uses: reggionick/s3-deploy@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: .                # upload everything from repo root
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          delete-removed: true     # remove files not in repo anymore
          no-cache: true           # disable caching so new versions load
          # NOTE: no "private" or ACL flags → avoids AccessControlListNotSupported
